services:
  - type: web
    name: myportfolio
    env: python
    buildCommand: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"
      pip install -r requirements.txt
    startCommand: gunicorn myportfolio.wsgi --log-file -
